#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = gcc
WINDRES = windres

INC = 
CFLAGS = -O2 -Wall
RESINC = 
LIBDIR = 
LIB = -lGL -lglut -lpthread -lm
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) 
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj
DEP_DEBUG = 
OUT_DEBUG = build/fhhrenderer

OBJ_DEBUG = $(OBJDIR_DEBUG)/entity/rectangle.o $(OBJDIR_DEBUG)/entity/sphere.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/material/glass.o $(OBJDIR_DEBUG)/material/lambertian.o $(OBJDIR_DEBUG)/entity/invert.o $(OBJDIR_DEBUG)/material/metal.o $(OBJDIR_DEBUG)/texture/checker_texture.o $(OBJDIR_DEBUG)/texture/constant_texture.o $(OBJDIR_DEBUG)/texture/image_texture.o $(OBJDIR_DEBUG)/algorithm/hitable_list.o $(OBJDIR_DEBUG)/algorithm/ray.o $(OBJDIR_DEBUG)/algorithm/reflect.o $(OBJDIR_DEBUG)/algorithm/refract.o $(OBJDIR_DEBUG)/algorithm/vec3.o $(OBJDIR_DEBUG)/entity/box.o $(OBJDIR_DEBUG)/entity/camera.o $(OBJDIR_DEBUG)/entity/cylinder.o

all: debug 

clean: clean_debug 

before_debug: 
	test -d build || mkdir -p build
	test -d $(OBJDIR_DEBUG)/entity || mkdir -p $(OBJDIR_DEBUG)/entity
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/material || mkdir -p $(OBJDIR_DEBUG)/material
	test -d $(OBJDIR_DEBUG)/texture || mkdir -p $(OBJDIR_DEBUG)/texture
	test -d $(OBJDIR_DEBUG)/algorithm || mkdir -p $(OBJDIR_DEBUG)/algorithm

after_debug: 
	strip $(OUT_DEBUG)
debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/entity/rectangle.o: entity/rectangle.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c entity/rectangle.c -o $(OBJDIR_DEBUG)/entity/rectangle.o

$(OBJDIR_DEBUG)/entity/sphere.o: entity/sphere.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c entity/sphere.c -o $(OBJDIR_DEBUG)/entity/sphere.o

$(OBJDIR_DEBUG)/main.o: main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.c -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/material/glass.o: material/glass.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c material/glass.c -o $(OBJDIR_DEBUG)/material/glass.o

$(OBJDIR_DEBUG)/material/lambertian.o: material/lambertian.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c material/lambertian.c -o $(OBJDIR_DEBUG)/material/lambertian.o

$(OBJDIR_DEBUG)/entity/invert.o: entity/invert.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c entity/invert.c -o $(OBJDIR_DEBUG)/entity/invert.o

$(OBJDIR_DEBUG)/material/metal.o: material/metal.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c material/metal.c -o $(OBJDIR_DEBUG)/material/metal.o

$(OBJDIR_DEBUG)/texture/checker_texture.o: texture/checker_texture.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c texture/checker_texture.c -o $(OBJDIR_DEBUG)/texture/checker_texture.o

$(OBJDIR_DEBUG)/texture/constant_texture.o: texture/constant_texture.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c texture/constant_texture.c -o $(OBJDIR_DEBUG)/texture/constant_texture.o

$(OBJDIR_DEBUG)/texture/image_texture.o: texture/image_texture.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c texture/image_texture.c -o $(OBJDIR_DEBUG)/texture/image_texture.o

$(OBJDIR_DEBUG)/algorithm/hitable_list.o: algorithm/hitable_list.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c algorithm/hitable_list.c -o $(OBJDIR_DEBUG)/algorithm/hitable_list.o

$(OBJDIR_DEBUG)/algorithm/ray.o: algorithm/ray.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c algorithm/ray.c -o $(OBJDIR_DEBUG)/algorithm/ray.o

$(OBJDIR_DEBUG)/algorithm/reflect.o: algorithm/reflect.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c algorithm/reflect.c -o $(OBJDIR_DEBUG)/algorithm/reflect.o

$(OBJDIR_DEBUG)/algorithm/refract.o: algorithm/refract.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c algorithm/refract.c -o $(OBJDIR_DEBUG)/algorithm/refract.o

$(OBJDIR_DEBUG)/algorithm/vec3.o: algorithm/vec3.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c algorithm/vec3.c -o $(OBJDIR_DEBUG)/algorithm/vec3.o

$(OBJDIR_DEBUG)/entity/box.o: entity/box.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c entity/box.c -o $(OBJDIR_DEBUG)/entity/box.o

$(OBJDIR_DEBUG)/entity/camera.o: entity/camera.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c entity/camera.c -o $(OBJDIR_DEBUG)/entity/camera.o

$(OBJDIR_DEBUG)/entity/cylinder.o: entity/cylinder.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c entity/cylinder.c -o $(OBJDIR_DEBUG)/entity/cylinder.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf build
	rm -rf $(OBJDIR_DEBUG)/entity
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/material
	rm -rf $(OBJDIR_DEBUG)/texture
	rm -rf $(OBJDIR_DEBUG)/algorithm


.PHONY: before_debug after_debug clean_debug

